POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Mike Vazovsky",
    "number": "123-456-7890"
}

### name filed is missing

POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "123-456-7890"
}

### name already exists

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Arto Hellas", 
    "number": "23213-231321"
}